project_id: '381767'
commit_message: 'chore(i18n/crowdin): updates for %original_file_name% (%language%)'
append_commit_message: false

files:
  - source: /src/languages/en-US/**/*.json
    translation: /src/languages/%locale%/**/%original_file_name%
