export const enum Events {
	ChannelCreate = 'channelCreate',
	ChannelDelete = 'channelDelete',
	ChannelUpdate = 'channelUpdate',
	EmojiCreate = 'emojiCreate',
	EmojiDelete = 'emojiDelete',
	EmojiUpdate = 'emojiUpdate',
	Error = 'error',
	GuildBanAdd = 'guildBanAdd',
	GuildBanRemove = 'guildBanRemove',
	GuildCreate = 'guildCreate',
	GuildDelete = 'guildDelete',
	GuildMemberAdd = 'guildMemberAdd',
	GuildMemberRemove = 'guildMemberRemove',
	GuildMemberUpdate = 'guildMemberUpdate',
	GuildMessageDelete = 'guildMessageDelete',
	GuildMessageLog = 'guildMessageLog',
	GuildMessageUpdate = 'guildMessageUpdate',
	GuildUpdate = 'guildUpdate',
	InviteCreate = 'inviteCreate',
	InviteDelete = 'inviteDelete',
	MessageCreate = 'messageCreate',
	MessageDelete = 'messageDelete',
	MessageUpdate = 'messageUpdate',
	RoleCreate = 'roleCreate',
	RoleDelete = 'roleDelete',
	RoleUpdate = 'roleUpdate',
	StageInstanceCreate = 'stageInstanceCreate',
	StageInstanceDelete = 'stageInstanceDelete',
	StageInstanceUpdate = 'stageInstanceUpdate',
	StickerCreate = 'stickerCreate',
	StickerDelete = 'stickerDelete',
	StickerUpdate = 'stickerUpdate',
	ThreadCreate = 'threadCreate',
	ThreadDelete = 'threadDelete',
	ThreadMembersUpdate = 'threadMembersUpdate',
	ThreadUpdate = 'threadUpdate',
	WebhookUpdate = 'webhookUpdate'
}

export const enum PermissionLevels {
	Everyone = 0,
	Moderator = 5,
	Administrator = 6,
	ServerOwner = 7,
	Developer = 10
}
