name: Create Sentry release

on:
    push:
        branches:
            - master
 
env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
    sentry-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
  
            - name: Get release
              id: get_release
              uses: pozetroninc/github-action-get-latest-release@master
              with:
                  owner: RTByte
                  repo: rtbyte
                  excludes: prerelease, draft
 
            - name: Create Sentry release
              uses: getsentry/action-release@v1
              env:
                SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
                SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
              with:
                environment: production
                version: ${{ steps.get_release.outputs.release }} 
